import { DebuggerWindow } from "debugger.slint";
import { Palette } from "std-widgets.slint";
export { DebuggerWindow }

export component MainWindow inherits Window {
    title: @tr("Aythya");

    MenuBar {
        Menu {
            title: @tr("File");

            MenuItem {
                title: @tr("Load...");
                activated => {
                    load();
                }
            }

            MenuItem {
                title: @tr("Quit");
                activated => {
                    quit();
                }
            }
        }

        Menu {
            title: @tr("Tools");

            MenuItem {
                title: @tr("Debugger");
                activated => {
                    show_debugger();
                }
            }
        }
    }

    VerticalLayout {
        Image {
            source: screen;
            image-fit: contain;
            image-rendering: pixelated;
        }
    }

    callback load();
    callback quit();
    callback show_debugger();

    in property <image> screen;
}
